### PR TITLE
Add ARM support

### PR DESCRIPTION
**Pull request by mauchede**
This PR should fix the issue #1.

List of changes:
* Add ARM support.
* Use "golang:1.6" for compilation.
* Use "alpine:latest" for tests.

### CODE REVIEW

**Comment by mauchede** [comment]
Hello @blackxored,

I added the support of ARM. I attached an [archive with the generated binaries](https://github.com/timonier/syslog-stdout/files/666540/syslog-stdout.tar.gz).

Can you check if all is OK for you?

**Comment by blackxored** [comment]
Thanks! Probably won't be able to test until the weekend, since it's a
little bit involved.

—
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by mauchede** [comment]
Hello @blackxored,

Did you have time to test the binaries?

**Comment by blackxored** [comment]
Hello,
Sorry for the late response. Yes I did have some succeed with them, thanks.

—
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by mauchede** [comment]
Perfect! I will merge this PR as soon as possible.

**Pull request closed without merging**
